#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument.
# which accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed and
# Ping the IP 5 times
    if [ "$#" -eq 1 ]
    then
        ping -c 5 "$1"
    else
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    fi
